1. Qinzhou Song qinzhounick@wustl.edu
Sicheng Yang sicheng@wustl.edu

2. 
[sicheng@iht32-1502 rustio]$ cargo run
   Compiling rustio v0.1.0 (/home/warehouse/sicheng/cse542/rustio)
    Finished dev [unoptimized + debuginfo] target(s) in 0.86s
     Running `target/debug/rustio`
x: 3 y: string z: 1.1

3.
[sicheng@iht32-1502 rustio]$ cargo run
   Compiling rustio v0.1.0 (/home/warehouse/sicheng/cse542/rustio)
warning: unused `Result` that must be used
 --> src/main.rs:8:5
  |
8 |     writeln!(std::io::stdout().lock(), "x: {x} y: {y} z: {z}");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this `Result` may be an `Err` variant, which should be handled
  = note: `#[warn(unused_must_use)]` on by default
  = note: this warning originates in the macro `writeln` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `rustio` (bin "rustio") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 1.02s
     Running `target/debug/rustio`
x: 3 y: string z: 1.1

4.
Output:
[sicheng@iht32-1502 rustio]$ cargo run
   Compiling rustio v0.1.0 (/home/warehouse/sicheng/cse542/rustio)
    Finished dev [unoptimized + debuginfo] target(s) in 0.92s
     Running `target/debug/rustio`
x: 3 y: string z: 1.1
Success

Code:
let x = 3;
let y = "string".to_string();
let z = 1.1;

let result = writeln!(std::io::stdout().lock(), "x: {x} y: {y} z: {z}");
match result {
    Err(e) => println!("Error {e} occur"),
    _ => println!("Success")
}

5.
output with filename:
[sicheng@iht32-1502 rustio]$ nano text.txt
[sicheng@iht32-1502 rustio]$ cargo run text.txt 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rustio text.txt`
x: 3 y: string z: 1.1
Success
Filename: text.txt
hello,
world!

output with non existing file:
[sicheng@iht32-1502 rustio]$ cargo run text2.txt 
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/rustio text2.txt`
x: 3 y: string z: 1.1
Success
Filename: text2.txt
Error No such file or directory (os error 2) occur when open file

6.
Output:
[sicheng@iht32-1502 rustio]$ cargo run text.txt 
   Compiling rustio v0.1.0 (/home/warehouse/sicheng/cse542/rustio)
    Finished dev [unoptimized + debuginfo] target(s) in 1.53s
     Running `target/debug/rustio text.txt`
x: 3 y: string z: 1.1
Success
Filename: text.txt
hello,
world!
end

Code:
let filename = &env::args().collect::<Vec<String>>()[1];
println!("Filename: {filename}");
let file = File::open(filename);
match file{
    Err(e) => println!("Error {e} occur when open file"),
    Ok(file) => {
        let f = BufReader::new(file);
        for line in f.lines(){
            match line{
                Ok(s) => if !s.is_empty() {println!("{s}")},
                _ => return
            }
        }
    }
}
